export const LOAD_POSTS = 'LOAD_POSTS'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const VIEW_SUBJECT_MATTER = 'VIEW_SUBJECT_MATTER'
export const VIEW_CAREER = 'VIEW_CAREER'
export const VIEW_STUDENTS = 'VIEW_STUDENTS'
export const ADD_CAREER = 'ADD_CAREER'